FROM python:3.12-slim

WORKDIR /app

ENV U2NET_HOME /app/u2net

COPY . .

RUN pip3 install --upgrade pip

RUN pip3 install -r requirements.txt

RUN apt update && apt install -y wget

RUN mkdir -p /app/u2net && wget https://huggingface.co/tomjackson2023/rembg/resolve/main/isnet-general-use.onnx?download=true -O /app/u2net/isnet-general-use.onnx

CMD ["python3", "server.py"]